server:
  port: 80

spring:
  application:
    name: cloud-order-service-consul
  cloud:
    consul:
      host: 106.14.217.80
      port: 8005
      discovery:
        service-name: ${spring.application.name}